//
// Created by lhx on 1/17/22.
//

#ifndef MYBLOCKCHAIN_COMPLIE_CONFIG_H
#define MYBLOCKCHAIN_COMPLIE_CONFIG_H
#define COORDINATOR_MIN_TRANSACTION_PER_WORKLOAD 10
#define COORDINATOR_MAX_TRANSACTION_PER_WORKLOAD 20
#define COORDINATOR_INPUT_MAX_BUFFER_SIZE 50

#endif //MYBLOCKCHAIN_COMPLIE_CONFIG_H
